name: Jar构建

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-windows-exe:
    runs-on: windows-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 配置Java环境
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Maven打包JAR包
        run: mvn clean package -DskipTests

      - name: 上传单独的Jar文件
        uses: actions/upload-artifact@v4
        with:
          name: java-jar
          path: ./target/SpigotCT-1.0-SNAPSHOT.jar

      - name: 创建压缩包
        run: |
          New-Item -ItemType Directory -Path ./dist -Force
          Copy-Item -Path ./target/SpigotCT-1.0-SNAPSHOT.jar -Destination ./dist/
          Copy-Item -Path ./res -Destination ./dist/ -Recurse -Force
          Compress-Archive -Path ./dist/* -DestinationPath ./SpigotCT-Windows.zip -Force

      - name: 上传打包好的压缩包
        uses: actions/upload-artifact@v4
        with:
          name: windows-jar-with-res
          path: ./SpigotCT-Windows.zip